namespace MonoCloud.Backend;

/// <summary>
/// Provides options to configure the MonoCloud authentication scheme for an ASP.NET Core application.
/// </summary>
public class MonoCloudAuthenticationOptions : AuthenticationSchemeOptions
{
  /// <inheritdoc />
  public MonoCloudAuthenticationOptions()
  {
    Events = new MonoCloudAuthenticationEvents();
    JwtTokenHandler.MapInboundClaims = _mapInboundClaims;
  }

  private bool _mapInboundClaims = true;

  /// <summary>
  /// Authority URL (issuer) expected during validation of tokens.
  /// This value should be the tenant domain.
  /// </summary>
  public string? TenantDomain { get; set; }

  /// <summary>
  /// Client identifier used for authentication
  /// </summary>
  public string? ClientId { get; set; }

  /// <summary>
  /// Represents the client authentication mechanism used during token validation or
  /// when making secure API calls. Checkout <see cref="ClientSecretAuth"/>, <see cref="JwtAssertionAuth"/> and <see cref="TlsAuth"/>
  /// </summary>
  public IMonoCloudClientAuth? ClientAuth { get; set; }

  /// <summary>
  /// Specifies the expected audience for the token validation.
  /// This value is used to match with the audience claim in the token
  /// to ensure the token is issued for the intended recipient.
  /// </summary>
  public string? Audience { get; set; }

  /// <summary>
  /// Handler for authentication-related events during the processing of the authentication workflow.
  /// Provides extensibility points via events that can be overridden to execute custom logic at various stages,
  /// such as token validation, assertion creation, or introspection.
  /// </summary>
  public new MonoCloudAuthenticationEvents Events
  {
    get => (MonoCloudAuthenticationEvents)base.Events!;
    set => base.Events = value;
  }

  /// <summary>
  /// Indicates whether caching is enabled for token introspection and validation processes.
  /// When enabled, reduces redundant network calls or computation by utilizing cached results.
  /// </summary>
  public bool EnableCaching { get; set; }

  /// <summary>
  /// Specifies the duration for which token claims are cached.
  /// This value determines the time span during which the claims are stored
  /// before they are revalidated or refreshed.
  /// </summary>
  public TimeSpan CacheDuration { get; set; } = TimeSpan.FromMinutes(5);

  /// <summary>
  /// Specifies a prefix to be applied to all cache keys generated by the caching mechanism.
  /// </summary>
  public string CacheKeyPrefix { get; set; } = string.Empty;

  /// <summary>
  /// Defines whether the bearer token should be stored in the
  /// <see cref="AuthenticationProperties"/> after a successful authorization.
  /// </summary>
  public bool SaveToken { get; set; }

  /// <summary>
  /// Specifies the amount of clock skew to tolerate during token validation.
  /// </summary>
  public TimeSpan? ClockSkew { get; set; }

  /// <summary>
  /// Specifies the duration for which the generated JWT assertion is valid before expiration.
  /// This property is used to calculate the expiration (`exp`) claim for the JWT assertion.
  /// The assertion will be cached for this duration to improve performance.
  /// </summary>
  public TimeSpan JwtAssertionDuration { get; set; } = TimeSpan.FromMinutes(5);

  /// <summary>
  /// Specifies the algorithm used for signing JWT assertions in client authentication flows.
  /// When not explicitly set, a default algorithm is typically applied.
  /// </summary>
  public string? JwtAssertionSigningAlgorithm { get; set; }

  /// <summary>
  /// Delegate used to determine whether certificate binding validation should be performed for the current request.
  /// </summary>
  public Func<HttpContext, bool> ValidateCertificateBinding { get; set; } = _ => false;

  /// <summary>
  /// A delegate function used to retrieve an X.509 certificate from the current HTTP context.
  /// This property allows customization of how the client certificate is accessed, providing
  /// the ability to handle scenarios where the certificate is needed for additional processing
  /// or authentication validation.
  /// </summary>
  public Func<HttpContext, Task<X509Certificate2?>> CertificateRetriever { get; set; } = async context => await context.Connection.GetClientCertificateAsync();

  /// <summary>
  /// Indicates whether JWT tokens must be introspected during authentication.
  /// When set to true, the handler validates the token using introspection,
  /// typically for scenarios where token validation is delegated to a remote authority.
  /// </summary>
  public bool IntrospectJwtTokens { get; set; }

  /// <summary>
  /// Specifies the authentication type associated with the identity,
  /// typically used for setting the claims identity's authentication method.
  /// If not explicitly set, the authentication scheme name will be used as the default value.
  /// </summary>
  public string? AuthenticationType { get; set; }

  /// <summary>
  /// Specifies the claim type to be used as the username in the identity.
  /// This value determines which claim in the token will be mapped to the user's identity name.
  /// </summary>
  public string? NameClaimType { get; set; }

  /// <summary>
  /// Specifies the claim type used to determine the roles of a user during token validation.
  /// </summary>
  public string? RoleClaimType { get; set; }

  /// <summary>
  /// Represents the OpenID configuration metadata.
  /// If this property is set, it will be used to initialize a <see cref="StaticConfigurationManager{T}"/>.
  /// Which is a static, pre-configured set of metadata instead of fetching it from a discovery endpoint.
  /// </summary>
  public OpenIdConnectConfiguration? Configuration { get; set; }

  /// <summary>
  /// This property provides access to the configured configuration manager, which is responsible for
  /// retrieving and caching the <see cref="OpenIdConnectConfiguration"/>.
  /// By default, it's configured to fetch metadata from the discovery endpoint.
  /// </summary>
  public IConfigurationManager<OpenIdConnectConfiguration>? ConfigurationManager { get; set; }

  /// <summary>
  /// Parameters used for validating JWT tokens.
  /// This property configures token validation settings such as issuer, audience,
  /// signing keys, and other security-related parameters to ensure the integrity and
  /// authenticity of received tokens during authentication.
  /// </summary>
  public TokenValidationParameters JwtTokenValidationParameters { get; set; } = new();

  /// <summary>
  /// Specifies the time interval after which the cached configuration is considered outdated and will be automatically refreshed
  /// when accessed. This helps ensure that the application always has up-to-date metadata
  /// about the identity provider, such as keys and endpoints, without requiring manual intervention.
  /// </summary>
  public TimeSpan AutomaticRefreshInterval { get; set; } = ConfigurationManager<OpenIdConnectConfiguration>.DefaultAutomaticRefreshInterval;

  /// <summary>
  /// Specifies the interval at which the configuration metadata (e.g., OpenID Connect discovery document)
  /// is retrieved to ensure the latest information is used for token validation.
  /// This property controls how frequently the metadata is refreshed in the background.
  /// </summary>
  public TimeSpan RefreshInterval { get; set; } = ConfigurationManager<OpenIdConnectConfiguration>.DefaultRefreshInterval;

  /// <summary>
  /// A delegate used to generate a unique cache key based on the provided
  /// authentication options and token. This is primarily used in conjunction
  /// with distributed caching of token-related data.
  /// </summary>
  public Func<MonoCloudAuthenticationOptions, string, string> CacheKeyGenerator { get; set; } = Utils.CacheKeyGenerator;

  /// <summary>
  /// Gets or sets the <see cref="MapInboundClaims"/> property on the internal <see cref="JsonWebTokenHandler"/> used for JWT validation, which is used when determining
  /// whether to map claim types that are extracted when validating a <see cref="JsonWebToken"/>.
  /// <para>If this is set to true, the Claim Type is set to the JSON claim 'name' after translating using this mapping. Otherwise, no mapping occurs.</para>
  /// <para>The default value is true.</para>
  /// </summary>
  public bool MapInboundClaims
  {
    get => _mapInboundClaims;
    set
    {
      _mapInboundClaims = value;
      JwtTokenHandler.MapInboundClaims = value;
    }
  }

  /// <summary>
  /// Indicates whether the token validation process should attempt to refresh the issuer's keys
  /// when a <see cref="SecurityTokenSignatureKeyNotFoundException"/> occurs.
  /// </summary>
  public bool RefreshOnIssuerKeyNotFound { get; set; }

  /// <summary>
  /// Provides an instance of <see cref="HttpClient"/> used to send HTTP requests
  /// and receive HTTP responses during authentication and token-related operations.
  /// This property is essential for managing HTTP communications, such as retrieving
  /// OpenID Connect configuration documents, performing token introspection,
  /// and handling certificate-based authentication in mutual TLS (mTLS) scenarios.
  /// </summary>
  public HttpClient HttpClient { get; set; } = null!;

  internal readonly JsonWebTokenHandler JwtTokenHandler = new();

  /// <summary>
  /// The authentication scheme name this options instance was configured for. Assigned during
  /// post-configuration and used to namespace cache entries so distinct schemes never share cached
  /// claims for the same token.
  /// </summary>
  internal string? SchemeName { get; set; }
}
